### ISSUE TITLE
"The private key is not present in the X.509 certificate."

### ISSUE THREAD

**Issue by EricDAllen** [Azure-Samples/active-directory-dotnet-daemon-certificate-credential#19] opened 2016-05-26 23:33 UTC
Hello-

I assume I've made a stupid mistake in generating my certificate.  Any idea why I would be seeing this exception message, when the client app tries to call authContext.AcquireTokenAsync()?

```
 "The private key is not present in the X.509 certificate."
```

Thanks for the sample and help!

**Comment by rahulrulez** [comment] 2016-09-24 13:38
I am facing the same issue

**Comment by builttoroamteam** [comment] 2016-10-14 03:30
Bump

**Comment by duckwaffle** [comment] 2016-10-14 03:31
Bump

**Comment by duckwaffle** [comment] 2016-10-14 05:12
Considering this question was asked almost 6 months ago and no one from the Azure team has been bothered to answer it, I'll post my solution here in case anyone runs across the same issue.

The problem is that instructions don't state that when creating the certificate for auth, because the private key is exported to a separate file you either have to a) install the private key to your personal keystore, or b) not export the private to a separate file, cause why would you? Seriously, just do it this way then you can export the public+private key together, or separately if you really want to from certmgr.

`makecert -r -pe -n "CN=TodoListDaemonWithCert" -ss My -len 2048 TodoListDaemonWithCert.cer`

Note the lack of "-sv TodoListDaemonPrivateKey.pvk", this ensured that when the certificate is added to your personal store with the private key associated.

**Comment by jmprieur** [comment] 2017-01-23 13:30
Thanks for your feedback.
Resolved by https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential/commit/9ec67e7ec6e23ebb0530fa70860d952a76975396

**Closed by jmprieur** 2017-01-23 13:30 UTC
